#!/bin/sh
# =============================================================================
# pfsense_safe_apply.sh
#
# PURPOSE:
#   Run this BEFORE making firewall changes via the pfSense web UI.
#   It snapshots the current config.xml and starts a 5-minute countdown.
#   If you do NOT confirm the changes in time, the config is automatically
#   reverted and all services are reloaded -- just like Windows display
#   settings rollback.
#
# USAGE:
#   sh pfsense_safe_apply.sh              # default 5-minute timeout
#   sh pfsense_safe_apply.sh 10           # custom timeout in minutes
#
# WORKFLOW:
#   1. Run this script
#   2. Make your changes in the pfSense web UI
#   3a. If changes work  -> run: sh pfsense_confirm_config.sh
#   3b. If changes break -> wait for auto-revert, OR run: sh pfsense_revert_config.sh
# =============================================================================

set -e

# --- Configuration -----------------------------------------------------------
PFSENSE_CONFIG="/cf/conf/config.xml"
BACKUP_DIR="/cf/conf/safe_apply_backups"
STATE_FILE="/tmp/safe_apply_state"
REVERT_SCRIPT="/tmp/pfsense_revert_config.sh"
CONFIRM_SCRIPT="/tmp/pfsense_confirm_config.sh"
TIMEOUT_MINUTES="${1:-5}"
TIMEOUT_SECONDS=$((TIMEOUT_MINUTES * 60))

# --- Sanity checks -----------------------------------------------------------
if [ ! -f "$PFSENSE_CONFIG" ]; then
    echo "[ERROR] pfSense config not found at: $PFSENSE_CONFIG"
    echo "        Are you running this on the pfSense machine?"
    exit 1
fi

# Check if a safe_apply session is already active
if [ -f "$STATE_FILE" ]; then
    OLD_PID=$(grep '^PID=' "$STATE_FILE" | cut -d= -f2)
    if kill -0 "$OLD_PID" 2>/dev/null; then
        echo "[WARNING] A safe_apply session is already running (PID: $OLD_PID)."
        echo "          To cancel it and start fresh, run:"
        echo "            sh $CONFIRM_SCRIPT   (accept current config, cancel old timer)"
        echo "          or kill the old timer manually: kill $OLD_PID"
        exit 1
    else
        echo "[INFO] Stale session found (PID $OLD_PID no longer running). Cleaning up."
        rm -f "$STATE_FILE"
    fi
fi

# --- Backup current config ---------------------------------------------------
mkdir -p "$BACKUP_DIR"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_FILE="${BACKUP_DIR}/config_backup_${TIMESTAMP}.xml"

cp "$PFSENSE_CONFIG" "$BACKUP_FILE"
echo "[OK] Config snapshot saved: $BACKUP_FILE"

# --- Write the revert script -------------------------------------------------
cat > "$REVERT_SCRIPT" << REVERT_EOF
#!/bin/sh
# Auto-generated by pfsense_safe_apply.sh -- DO NOT EDIT MANUALLY
BACKUP_FILE="$BACKUP_FILE"
PFSENSE_CONFIG="$PFSENSE_CONFIG"
STATE_FILE="$STATE_FILE"

echo ""
echo "============================================"
echo "  SAFE APPLY: TIMER EXPIRED -- REVERTING"
echo "============================================"
echo "  Restoring: \$BACKUP_FILE"
echo "  Time: \$(date)"
echo ""

# Restore the backed-up config
cp "\$BACKUP_FILE" "\$PFSENSE_CONFIG"

if [ \$? -eq 0 ]; then
    echo "[OK] config.xml restored successfully."
else
    echo "[ERROR] Failed to restore config.xml!"
    exit 1
fi

# Reload all pfSense services to apply the restored config
echo "[INFO] Reloading pfSense services..."
/etc/rc.reload_all start 2>&1

echo ""
echo "[DONE] Revert complete. pfSense is running the previous configuration."
echo "       You can now safely log back in."

# Clean up state file
rm -f "\$STATE_FILE"
REVERT_EOF

chmod +x "$REVERT_SCRIPT"

# --- Write the confirm script ------------------------------------------------
cat > "$CONFIRM_SCRIPT" << CONFIRM_EOF
#!/bin/sh
# Auto-generated by pfsense_safe_apply.sh -- DO NOT EDIT MANUALLY
STATE_FILE="$STATE_FILE"
BACKUP_FILE="$BACKUP_FILE"

if [ ! -f "\$STATE_FILE" ]; then
    echo "[INFO] No active safe_apply session found. Nothing to confirm."
    exit 0
fi

PID=\$(grep '^PID=' "\$STATE_FILE" | cut -d= -f2)

echo ""
echo "============================================"
echo "  SAFE APPLY: CONFIRMING NEW CONFIG"
echo "============================================"

if [ -n "\$PID" ] && kill -0 "\$PID" 2>/dev/null; then
    kill "\$PID" 2>/dev/null
    echo "[OK] Revert timer cancelled (killed PID \$PID)."
else
    echo "[INFO] Revert timer was not running (may have already completed)."
fi

echo "[OK] Current pfSense configuration is now permanent."
echo "     Backup retained at: \$BACKUP_FILE"
echo ""

rm -f "\$STATE_FILE"
CONFIRM_EOF

chmod +x "$CONFIRM_SCRIPT"

# --- Launch background revert timer ------------------------------------------
# Run in background: sleep, then execute revert
(sleep "$TIMEOUT_SECONDS" && sh "$REVERT_SCRIPT") &
TIMER_PID=$!

# Save session state
cat > "$STATE_FILE" << STATE_EOF
PID=$TIMER_PID
BACKUP=$BACKUP_FILE
STARTED=$(date +"%Y-%m-%d %H:%M:%S")
TIMEOUT_MINUTES=$TIMEOUT_MINUTES
STATE_EOF

# --- Summary -----------------------------------------------------------------
echo ""
echo "============================================"
echo "  SAFE APPLY SESSION STARTED"
echo "============================================"
echo "  Backup:       $BACKUP_FILE"
echo "  Timer PID:    $TIMER_PID"
echo "  Revert in:    $TIMEOUT_MINUTES minute(s) (at $(date -v+${TIMEOUT_MINUTES}M +"%H:%M:%S" 2>/dev/null || date --date="${TIMEOUT_MINUTES} minutes" +"%H:%M:%S" 2>/dev/null || echo "~${TIMEOUT_MINUTES} min from now"))"
echo ""
echo "  >> Make your changes in the pfSense web UI now <<"
echo ""
echo "  To ACCEPT changes (cancel revert timer):"
echo "    sh $CONFIRM_SCRIPT"
echo ""
echo "  To REVERT immediately (don't wait for timer):"
echo "    sh $REVERT_SCRIPT"
echo "============================================"
